# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

ame: Deploy to Azure

on:
  push:
    branches:
      - master  # Déclencher le pipeline lorsque des modifications sont poussées sur la branche master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    
    steps:
    # 1. Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # 2. Setup Python
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Spécifiez la version de Python que vous utilisez
    
      - name: Create and start virtual environment
        run: |
          cd app
          python -m venv venv
          source venv/bin/activate
          run: pip install -r requirements.txt
        
      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            release.zip
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_08DCC71D89544854991057FA40C3D8F6 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_B7B30F251C65448897B468A1C99308BA }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_B3DF032DA5E74109AFFA02DDCDD6375E }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'appwebmodel'
          slot-name: 'Production'
          
