name: Deploy to Azure

on:
  push:
    branches:
      - master  # Déclencher le pipeline lorsque des modifications sont poussées sur la branche master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    
    steps:
    # 1. Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # 2. Setup Python
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Spécifiez la version de Python que vous utilisez
    
    # 3. Install dependencies
    - name: Install dependencies
      run: |
        python -m venv .venv
        source .venv/bin/activate
        pip install -r requirements.txt

    # 4. Run tests (optional)
    - name: Run tests
      run: |
        source .venv/bin/activate
        pytest  # Vous pouvez remplacer cette commande par la vôtre si vous utilisez un autre framework de test

    # 5. Deploy to Azure Web App
    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'scoringmodel'  # Remplacez par le nom de votre application Azure
        slot-name: 'production'  # Vous pouvez changer le slot selon vos besoins (par défaut 'production')
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}  # Utilisez les secrets GitHub pour stocker les credentials Azure
